# web server configuration

classification:
  inference:
    model_path: staged/clf.pkl
    api_prefix: /classification/inference
    api_tags:
      - Santander Customesr Transaction Prediction

server:
  host: 0.0.0.0
  port: 8000
  api_prefix: /api/v1
