name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF_ACCESS_TOKEN }}
        run: git remote add space https://SahilAhuja:$HF@huggingface.co/spaces/SahilAhuja/santander-customer-transaction-app
      - name: Push to hub
        env:
          HF: ${{ secrets.HF_ACCESS_TOKEN }}
        run: git push --force https://SahilAhuja:$HF@huggingface.co/spaces/noahgift/demo main