name: Santander Customer Transaction App

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install unittest dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-unittest.txt
    - name: Run tests
      run: |
        python -m pytest
